name: .NET CI/CD Production Deployment Pipeline

on:
  push:
    branches
      - main # Trigger the workflow everytime you push to the main branch

jobs:
  deploy: 
    runs-on: ubuntu-latest # Use a Github-hosted runner
    steps:
      - name: Execute script on remote server
      # Excute the server's bash script remotely using the workflow
        uses: appleboy/ssh-action@v1.0.3 # use ssh actions to excute
        with:
          host: ${{ secrets.SERVER_IP }} # the host server's public ip address
          username: ubuntu
          password: ${{ secrets.PASSWORD }} # password of the server
          script: |
            /home/ubuntu/Deployment/deploy-app-package.sh
